services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db_postgres:
        condition: service_healthy
    volumes:
      - .:/app
    
  # CAJA NUEVA: POSTGRESQL
  db_postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tienda_fastapi
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usuario -d tienda_fastapi"]
      interval: 5s
      timeout: 5s
      retries: 5